[package]
name = "tonic-flatbuffers-build"
description = "Generates tonic-compatible gRPC stubs for flatbuffers RPC services."
version.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
flatbuffers-build = { version = "0.2.2+flatc-25.2.10", features = ["vendored"] }
itertools = "0.14.0"
prettyplease = "0.2.20"
protobuf-src = { version = "2.1.1", optional = true }
regex = "1.10.6"
syn = { version = "2.0.74" }
tempfile = "3.20.0"
tonic-build = "0.13.1"

[features]
vendored = ["flatbuffers-build/vendored", "dep:protobuf-src"]
default = ["vendored"]
